// lib/texts/ChapterTwo.dart

const String chapterTwo = '''The Upanishads (/ʊˈpʌnɪʃədz/; Sanskrit: उपनिषद्, IAST: Upaniṣad, pronounced [ˈʊpɐnɪʂɐd]) are late Vedic and post-Vedic Sanskrit texts that "document the transition from the archaic ritualism of the Veda into new religious ideas and institutions" and the emergence of the central religious concepts of Hinduism. They are the most recent addition to the Vedas, the oldest scriptures of Hinduism, and deal with meditation, philosophy, consciousness, and ontological knowledge. Earlier parts of the Vedas dealt with mantras, benedictions, rituals, ceremonies, and sacrifices.

While among the most important literature in the history of Indian religions and culture, the Upanishads document a wide variety of "rites, incantations, and esoteric knowledge" departing from Vedic ritualism and interpreted in various ways in the later commentarial traditions. The Upanishads are widely known, and their diverse ideas, interpreted in various ways, informed later traditions of Hinduism. The central concern of all Upanishads is to discover the relations between ritual, cosmic realities (including gods), and the human body/person, postulating Ātman and Brahman as the "summit of the hierarchically arranged and interconnected universe," but various ideas about the relation between Atman and Brahman can be found.

Around 108 Upanishads are known, of which the first dozen or so are the oldest and most important and are referred to as the principal or main (mukhya) Upanishads. The mukhya Upanishads are found mostly in the concluding part of the Brahmanas and Aranyakas and were, for centuries, memorized by each generation and passed down orally. The mukhya Upanishads predate the Common Era, but there is no scholarly consensus on their date, or even on which ones are pre- or post-Buddhist. The Brhadaranyaka is seen as particularly ancient by modern scholars. Of the remainder, 95 Upanishads are part of the Muktikā canon, composed from about the last centuries of 1st-millennium BCE through about 15th-century CE. New Upanishads, beyond the 108 in the Muktika canon, continued to be composed through the early modern and modern era, though often dealing with subjects that are unconnected to the Vedas. The mukhya Upanishads, along with the Bhagavad Gita and the Brahmasutra (known collectively as the Prasthanatrayi), are interpreted in divergent ways in the several later schools of Vedanta.

Translations of the Upanishads in the early 19th century started to attract attention from a Western audience. German philosopher Arthur Schopenhauer was deeply impressed by the Upanishads and called them "the most profitable and elevating reading which ... is possible in the world." Modern era Indologists have discussed the similarities between the fundamental concepts in the Upanishads and the works of major Western philosophers.

• The Isha Upanishad (Sanskrit: ईशोपनिषद्, IAST: Īśopaniṣad), also known as Shri Ishopanishad, Ishavasya Upanishad, or Vajasaneyi Samhita Upanishad, is one of the shortest Upanishads, embedded as the final chapter (adhyāya) of the Shukla Yajurveda. It is a Mukhya (primary, principal) Upanishad, and is known in two recensions, called Kanva (VSK) and Madhyandina (VSM). The Upanishad is a brief poem, consisting of 17 or 18 verses, depending on the recension.
It is a key scripture of the Vedanta sub-schools, and an influential Śruti to diverse schools of Hinduism. It is the 40th chapter of Yajurveda. The name of the text derives from its incipit, īśā vāsyam, "enveloped by the Lord", or "hidden in the Lord (Self)". 
The text discusses the Atman (Self) theory of Hinduism, and is referenced by both Dvaita (dualism) and Advaita (non-dualism) sub-schools of Vedanta.
It is classified as a "poetic Upanishad" along with Kena, Katha, Svetasvatara and Mundaka by Paul Deussen (1908).

• The Kena Upanishad (Sanskrit: केनोपनिषद्, IAST: Kenopaniṣad) (also alternatively known as Talavakara Upanishad) is a Vedic Sanskrit text classified as one of the primary or Mukhya Upanishads that is embedded inside the last section of the Talavakara Brahmanam of the Samaveda. It is listed as number 2 in the Muktikā, the canon of the 108 Upanishads of Hinduism.
The Kena Upanishad was probably composed sometime around the middle of the 1st millennium BCE. It has an unusual structure where the first 13 are verses composed as a metric poem, followed by 15 prose paragraphs of main text plus 6 prose paragraphs of epilogue. Paul Deussen suggests that the latter prose section of the main text is far more ancient than the poetic first section, and Kena Upanishad bridged the more ancient prose Upanishad era with the metric poetic era of Upanishads that followed.
Kena Upanishad is notable in its discussion of Brahman with attributes and without attributes, and for being a treatise on "purely conceptual knowledge". It asserts that the efficient cause of all the gods, symbolically envisioned as forces of nature, is Brahman. This has made it a foundational scripture to Vedanta school of Hinduism, both the theistic and monistic sub-schools after varying interpretations. The Kena Upanishad is also significant in asserting the idea of "Spiritual Man", "Self is a wonderful being that even gods worship", "Atman (Self) exists", and "knowledge and spirituality are the goals and intense longing of all creatures".

• The Mundaka Upanishad (Sanskrit: मुण्डकोपनिषद्, Muṇḍakopaniṣad) is an ancient Sanskrit Vedic text, embedded inside Atharva Veda. It is a Mukhya (primary) Upanishad, and is listed as number 5 in the Muktika canon of 108 Upanishads of Hinduism. It is among the most widely translated Upanishads.
It is presented as a dialogue between sage Saunaka and sage Angiras. It is a poetic verse style Upanishad, with 64 verses, written in the form of mantras. However, these mantras are not used in rituals, rather they are used for teaching and meditation on spiritual knowledge.
The Mundaka Upanishad contains three Mundakams (parts), each with two khandas (sections). The first Mundakam, states Roer, defines the science of "Higher Knowledge" and "Lower Knowledge", and then asserts that acts of oblations and pious gifts are foolish, and do nothing to reduce unhappiness in current life or next, rather it is knowledge that frees. The second Mundakam describes the nature of the Brahman, the Self, the relation between the empirical world and the Brahman, and the path to know Brahman. The third Mundakam expands the ideas in the second Mundakam and then asserts that the state of knowing Brahman is one of freedom, fearlessness, complete liberation, self-sufficiency and bliss.
Some scholars suggest that passages in the Mundaka Upanishad present the pantheism theory.
In some historic Indian literature and commentaries, the Mundaka Upanishad is included in the canon of several verse-structured Upanishads that are collectively referred to as "Mantra Upanishad" or "Mantropanishad".

• The Mandukya Upanishad (Sanskrit: माण्डूक्योपनिषद्, IAST: Māṇḍūkyopaniṣad) is the shortest of all the Upanishads, and is assigned to Atharvaveda. It is listed as number 6 in the Muktikā canon of 108 Upanishads.
It is in prose, consisting of twelve short verses, and is associated with a Rig Vedic school of scholars. It discusses the syllable Aum; adds turya to the three states of consciousness; and asserts that Aum is Brahman – which is the Whole – and that Brahman is this self (ātman).
The Mandukya Upanishad is recommended in the Muktikā Upanishad, in a dialogue between two of the most important characters of the Ramayana, Rama and Hanuman, as the one Upanishad that alone is sufficient for knowledge to gain moksha, and as sixth in its list of ten principal Upanishads. The text is also notable for inspiring Gaudapada's Mandukya Karika a classic for the Vedanta school of Hinduism. The Mandukya Upanishad is among the often-cited texts on chronology and the philosophical relationship between Hinduism and Buddhism. ''';
