// lib/texts/chapterTwo.dart

const String chapterOne = '''The Vedas (/ˈveɪdəz/ or /ˈviːdəz/; Sanskrit: वेदः, romanized: Vēdaḥ, lit. 'knowledge') are a large body of religious texts originating in ancient India. Composed in Vedic Sanskrit, the texts constitute the oldest layer of Sanskrit literature and the oldest scriptures of Hinduism.

There are four Vedas: the Rigveda, the Yajurveda, the Samaveda and the Atharvaveda. Each Veda has four subdivisions – the Samhitas (mantras and benedictions), the Brahmanas (commentaries on and explanation of rituals, ceremonies and sacrifices - Yajñas), the Aranyakas (text on rituals, ceremonies, sacrifices and symbolic-sacrifices), and the Upanishads (texts discussing meditation, philosophy and spiritual knowledge). Some scholars add a fifth category – the Upāsanās (worship).

The texts of the Upanishads discuss ideas akin to the heterodox sramana traditions. The Samhitas and Brahmanas describe daily rituals and are generally meant for Brahmacharya and Gr̥hastha stages of the Chaturashrama system, while the Aranyakas and Upanishads are meant for the Vānaprastha and Sannyasa stages, respectively.

Vedas are śruti ("what is heard"), distinguishing them from other religious texts, which are called smr̥ti ("what is remembered"). Hindus consider the Vedas to be apauruṣeya, which means "not of a man, superhuman" and "impersonal, authorless", revelations of sacred sounds and texts heard by ancient sages after intense meditation.

The Vedas have been orally transmitted since the 2nd millennium BCE with the help of elaborate mnemonic techniques. The mantras, the oldest part of the Vedas, are recited in the modern age for their phonology rather than the semantics, and are considered to be "primordial rhythms of creation", preceding the forms to which they refer. By reciting them the cosmos is regenerated, "by enlivening and nourishing the forms of creation at their base."

The various Indian philosophies and Hindu sects have taken differing positions on the Vedas. Schools of Indian philosophy that acknowledge the importance or primal authority of the Vedas comprise Hindu philosophy specifically and are together classified as the six "orthodox" (āstika) schools. However, śramaṇa traditions, such as Charvaka, Ajivika, Buddhism, and Jainism, which did not regard the Vedas as authoritative, are referred to as "heterodox" or "non-orthodox" (nāstika) schools.

• The Rigveda or Rig Veda (Sanskrit: ऋग्वेद, IAST: ṛgveda, from ऋच्, "praise" and वेद, "knowledge") is an ancient Indian collection of Vedic Sanskrit hymns (sūktas). It is one of the four sacred canonical Hindu texts (śruti) known as the Vedas. Only one Shakha of the many survive today, namely the Śakalya Shakha. Much of the contents contained in the remaining Shakhas are now lost or are not available in the public forum.

The Rigveda is the oldest known Vedic Sanskrit text. Its early layers are among the oldest extant texts in any Indo-European language. The sounds and texts of the Rigveda have been orally transmitted since the 2nd millennium BCE. Philological and linguistic evidence indicates that the bulk of the Rigveda Samhita was composed in the northwestern region of the Indian subcontinent (see Rigvedic rivers), most likely between c. 1500 and 1000 BCE, although a wider approximation of c. 1900–1200 BCE has also been given.

The text is layered, consisting of the Samhita, Brahmanas, Aranyakas and Upanishads. The Rigveda Samhita is the core text and is a collection of 10 books (maṇḍalas) with 1,028 hymns (sūktas) in about 10,600 verses (called ṛc, eponymous of the name Rigveda). In the eight books – Books 2 through 9 – that were composed the earliest, the hymns predominantly discuss cosmology, rites required to earn the favour of the gods, as well as praise them. The more recent books (Books 1 and 10) in part also deal with philosophical or speculative questions, virtues such as dāna (charity) in society, questions about the origin of the universe and the nature of the divine, and other metaphysical issues in their hymns.

Some of its verses continue to be recited during Hindu prayer and celebration of rites of passage (such as weddings), making it probably the world's oldest religious text in continued use.

• The Yajurveda (Sanskrit: यजुर्वेद, IAST: yajurveda, from यजुस्, "worship", and वेद, "knowledge") is the Veda primarily of prose mantras for worship rituals. An ancient Vedic Sanskrit text, it is a compilation of ritual-offering formulas that were said by a priest while an individual performed ritual actions such as those before the yajna fire. Yajurveda is one of the four Vedas, and one of the scriptures of Hinduism. The exact century of Yajurveda's composition is unknown, and estimated by Witzel to be between 1200 and 800 BCE, contemporaneous with Samaveda and Atharvaveda.

The Yajurveda is broadly grouped into two: the "black" or "dark" (Krishna) Yajurveda and the "white" or "bright" (Shukla) Yajurveda. The term "black" implies "the un-arranged, unclear, motley collection" of verses in Yajurveda, in contrast to the "white" which implies the "well arranged, clear" Yajurveda. The black Yajurveda has survived in four recensions, while two recensions of white Yajurveda have survived into modern times.

The earliest and most ancient layer of Yajurveda samhita includes about 1,875 verses, that are distinct yet borrow and build upon the foundation of verses in Rigveda. The middle layer includes the Satapatha Brahmana, one of the largest Brahmana texts in the Vedic collection. The youngest layer of Yajurveda text includes the largest collection of primary Upanishads, influential to various schools of Hindu philosophy. These include the Brihadaranyaka Upanishad, the Isha Upanishad, the Taittiriya Upanishad, the Katha Upanishad, the Shvetashvatara Upanishad and the Maitri Upanishad.

Two of the oldest surviving manuscript copies of the Shukla Yajurveda sections have been discovered in Nepal and Western Tibet, and these are dated to the 12th-century CE.

• The Samaveda (Sanskrit: सामवेद, IAST: Sāmaveda, from सामन्, "song" and वेद, "knowledge"), is the Veda of melodies and chants. It is an ancient Vedic Sanskrit text, and is one of the sacred scriptures in Hinduism. One of the four Vedas, it is a liturgical text which consists of 1,875 verses. All but 75 verses have been taken from the Rigveda. Three recensions of the Samaveda have survived, and variant manuscripts of the Veda have been found in various parts of India.

While its earliest parts are believed to date from as early as the Rigvedic period, the existing samhita text dates from the post-Rigvedic Mantra period of Vedic Sanskrit, between c. 1200 and 1000 BCE or "slightly rather later," roughly contemporary with the Atharvaveda and the Yajurveda. Along with the Samhita layer of text, the Samaveda includes Brahmana texts, and a final layer of the text that covers philosophical speculations (Upanishads). These layers of the compilation dates from the post-Rigvedic Mantra period of Vedic Sanskrit, likely around the 6th century BCE.

Embedded inside the Samaveda are the widely studied Chandogya Upanishad and Kena Upanishad. These Upanishads are considered as primary Upanishads and have had influence on the six schools of Hindu philosophy, particularly the Vedanta school. The Samaveda laid important foundations for subsequent Indian music.

It is also referred to as Sama Veda.

• The Atharvaveda or Atharva Veda (Sanskrit: अथर्ववेद, IAST: Atharvaveda, from अथर्वन्, "priest" and वेद, "knowledge") or Atharvana Veda (Sanskrit: अथर्वणवेद, IAST: Atharvaṇaveda) is the "knowledge storehouse of atharvāṇas, the procedures for everyday life". The text is the fourth Veda, and is a late addition to the Vedic scriptures of Hinduism

The language of the Atharvaveda is different from Rigvedic Sanskrit, preserving pre-Vedic Indo-European archaisms.  It is a collection of 730 hymns with about 6,000 mantras, divided into 20 books. About a sixth of the Atharvaveda texts adapts verses from the Rigveda, and except for Books 15 and 16, the text is mainly in verse deploying a diversity of Vedic meters. Two different recensions of the text – the Paippalāda and the Śaunakīya – have survived into modern times. Reliable manuscripts of the Paippalada edition were believed to have been lost, but a well-preserved version was discovered among a collection of palm leaf manuscripts in Odisha in 1957.

The Atharvaveda is sometimes called the "Veda of magical formulas", a description considered incorrect by other scholars. In contrast to the 'hieratic religion' of the other three Vedas, the Atharvaveda is said to represent a 'popular religion', incorporating not only formulas for magic, but also the daily rituals for initiation into learning (upanayana), marriage and funerals. Royal rituals and the duties of the court priests are also included in the Atharvaveda.

The Atharvaveda was likely compiled as a Veda contemporaneously with Samaveda and Yajurveda, or about 1200 BCE – 1000 BCE. Along with the Samhita layer of text, the Atharvaveda includes a Brahmana text, and a final layer of the text that covers philosophical speculations. The latter layer of Atharvaveda text includes three primary Upanishads, influential to various schools of Hindu philosophy. These include the Mundaka Upanishad, the Mandukya Upanishad and the Prashna Upanishad.''';
